---
- name: Install requirements
  apt: name={{ item }}
  with_items:
    - python-setuptools
    - sqlite3
    - rsync

- name: Install python dependencies
  easy_install: name={{ item }}
  with_items:
    - pip
    - bottle
    - tornado

- name: Create user
  user: createhome=yes name=crash

- name: Copy service
  synchronize:
    src: "{{ playbook_dir }}/../services/crash/"
    dest: "/home/crash/"
    recursive: yes
    use_ssh_args: yes

- name: Fix permissions
  file: name="/home/crash" state=directory owner=crash recurse=yes

- name: Add systemd service
  template: src=service.j2 dest=/lib/systemd/system/crash.service

- name: Enable service
  service: name=crash enabled=yes

- name: Start service
  service: name=crash state=started
