---
- name: Install lxc
  apt: pkg={{ item }} default_release=testing
  with_items:
    - lxc
    - lxc-dev
    - debootstrap
    - python
    - python-pip
    - python-dev

- name: Install lxc-python2
  pip: name=lxc-python2

- name: Create lxc-net
  template: src=lxc-net.j2 dest=/etc/default/lxc-net
  register: lxc_net

- name: Create lxc default.conf
  template: src=default.conf.j2 dest=/etc/lxc/default.conf
  register: lxc_conf

- name: Add lxc-net to resolv.conf
  lineinfile: dest=/etc/resolv.conf line="nameserver 192.168.254.254" insertafter=EOF

- name: Enable lxc-net
  service: name=lxc-net enabled=yes

- name: Restart lxc-net
  service: name=lxc-net state=restarted
  when: "lxc_net.changed or lxc_conf.changed"
  tags:
    - skip_ansible_lint

- name: Enable forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: Create lxc container
  lxc_container:
    name: "{{ item.name }}"
    state: started
    backing_store: loop
    fs_size: "2G"
    template: debian
    template_options: "--mirror=http://mirror.yandex.ru/debian --security-mirror=http://mirror.yandex.ru/debian --packages=python,sudo,apt-utils,ca-certificates"
    container_config:
      - "lxc.cgroup.memory.limit_in_bytes = {{ item.mem | default(512000000) }}"
      - "lxc.cgroup.memory.memsw.limit_in_bytes = {{ item.mem | default(512000000) }}"
    container_command: |
      sed -i 's/PermitRootLogin\s*without-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
      mkdir -p /root/.ssh/
      echo "{{ SSH_PUBLIC_KEY }}" > /root/.ssh/authorized_keys
      systemctl restart ssh
      bash
  with_items:
    - { name: build, mem: 1000000000 }
    - { name: cartographer }
    - { name: crash }
    - { name: atlablog }
    - { name: sapmarine }
    - { name: thebin, mem: 256000000 }
    - { name: weather, mem: 256000000 }
