---
- name: Enable swappaccount and memory limit
  lineinfile:
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet swapaccount=1 cgroup_enable=memory"'
    dest: "/etc/default/grub"
  register: grub

- name: Update grub
  command: update-grub
  when: grub.changed

- name: Restart image
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: grub.changed

- name: waiting for image to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=5 timeout=100
  become: false
  when: grub.changed

- name: Add backports repo
  apt_repository: repo="deb http://mirror.yandex.ru/debian jessie-backports main" state=present update_cache=yes

- name: Install lxc
  apt: pkg={{ item }} state=latest default_release=jessie-backports
  with_items:
    - lxc
    - lxc-dev
    - debootstrap
    - python
    - python-pip
    - python-dev

- name: Install lxc-python2
  pip: name=lxc-python2 state=latest

- name: Create lxc-net
  template: src=lxc-net.j2 dest=/etc/default/lxc-net

- name: Create lxc default.conf
  template: src=default.conf.j2 dest=/etc/lxc/default.conf

- name: Add lxc-net to resolv.conf
  lineinfile: dest=/etc/resolv.conf line="nameserver 192.168.254.254" insertbefore=BOF

- name: Enable lxc-net
  service: name=lxc-net state=restarted enabled=yes

- name: Enable forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: Create lxc container
  lxc_container:
    name: "{{ item.name }}"
    template: debian
    state: started
    backing_store: loop
    fs_size: "4G"
    container_log: true
    container_config:
      - "lxc.cgroup.memory.limit_in_bytes = {{ item.mem }}"
      - "lxc.cgroup.memory.memsw.limit_in_bytes = {{ item.mem }}"
    container_command: |
      sed -i 's/PermitRootLogin\s*without-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
      systemctl restart ssh
      mkdir -p /root/.ssh/
      echo "{{ SSH_PUBLIC_KEY }}" >> /root/.ssh/authorized_keys
      bash
  with_items:
    - { name: nginx, mem: "512000000" }
    - { name: service1, mem: "512000000" }
    # - { name: service2, mem: "512000000" }
    # - { name: service3, mem: "512000000" }

