- name: set timezone to Asia/Yekaterinburg
  file: src=/usr/share/zoneinfo/Asia/Yekaterinburg dest=/etc/localtime state=link force=yes
  notify: update timezone

- name: copy network configs for eth0 and eth1
  template: src={{item}}.j2 dest=/etc/network/interfaces.d/{{item}}.cfg
  with_items:
    - 60-internal_network
    - 65-external_network
  
- name: remove old network config
  file: path=/etc/network/interfaces.d/50-cloud-init.cfg state=absent

- name: generate locales
  locale_gen: name={{item}} state=present
  with_items:
    - en_US.UTF-8
    - ru_RU.UTF-8

- name: set hostname
  hostname: name={{inventory_hostname}}

- name: copy hostname file
  copy: content={{inventory_hostname}} dest=/etc/hostname

- name: place /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts

- name: install basic packages
  apt: name={{item}} state=latest
  with_items:
    - python-pip
    - htop
    - iperf
    - mc
    - tmux

- name: set limits
  copy: src=limits.conf dest=/etc/security/limits.conf

- name: place .bashrc to root
  copy: src=.bashrc dest=/root/.bashrc

- name: place .bashrc to ubuntu user
  copy: src=.bashrc dest=/home/ubuntu/.bashrc owner=ubuntu
