---
- name: Install requirements
  apt: name={{ item }}
  with_items:
    - libssl-dev
    - make
    - g++

- name: Copy service
  copy:
    src: "{{ playbook_dir }}/../services/thebin/"
    dest: "/opt/thebin/"

- name: Make rand
  make: chdir=/opt/thebin/ target=rand.so

- name: Fetch rand.so
  fetch: src=/opt/thebin/rand.so dest="{{ playbook_dir }}/../services/thebin/rand.so" flat=yes
