- name: set sysctl settings
  sysctl:  name={{item}} value=1 state=present
  with_items:
    - net.ipv4.tcp_thin_linear_timeouts
    - net.ipv4.tcp_thin_dupack

- name: systemd configs
  template: src=worker-checkers.service.j2 dest=/etc/systemd/system/worker-checkers.service
  with_items:
    - { jobs: 600 }

- name: systemd reload
  command: systemctl daemon-reload

- name: catalog for checkers
  file: path={{cs_dir}}/app/checkers state=directory

- name: checker deps
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - nodejs-legacy
    - npm
    - python3-pip
    - libfontconfig
    - docker.io
    - libc6-i386
    - python3-crypto

- name: selenium checker npm deps
  npm: name=phantomjs global=yes

- name: checker python deps
  pip: executable=pip3 name={{item}}
  with_items:
    - selenium
    - Pillow
    - requests
    - grequests
    - aiohttp

- name: checkers
  synchronize: src=../../../../checkers dest={{cs_dir}}/app

- name: crash dumps
  file: path={{cs_dir}}/app/checkers/crash/dumps state=directory

- name: checkers owner
  file: path={{cs_dir}}/app/checkers/ owner={{cs_user}} group={{cs_user}} recurse=yes
