---
- name: Install requirements
  apt: name={{ item }} default_release=testing
  with_items:
    - libssl-dev
    - make
    - g++

- name: Copy service
  copy:
    src: "{{ playbook_dir }}/../services/pastebin/"
    dest: "/opt/pastebin/"

- name: Make rand
  make: chdir=/opt/pastebin/ target=rand.so

- name: Fetch rand.so
  fetch: src=/opt/pastebin/rand.so dest="{{ playbook_dir }}/../services/pastebin/rand.so" flat=yes
