---
- name: Copy service
  copy:
    src: "{{ playbook_dir }}/../services/sapmarine/"
    dest: "/opt/sapmarine/"
    owner: sapmarine

- name: Build project
  command: swift build -c release --build-path /opt/sapmarine/bin/
  args:
    chdir: /opt/sapmarine/
  environment:
    PATH: "/opt/swift-3.0-RELEASE-ubuntu14.04/usr/bin:{{ ansible_env.PATH }}"

- name: Fetch binary
  fetch: src=/opt/sapmarine/bin/release/ dest="/tmp/sapmarine/" flat=yes
