- name: ensure user
  user: name={{cs_user}} state=present

- name: ensure common requirements
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - libssl-dev
    - libpq-dev
    - cpanminus
    - git
    - build-essential

- name: clone repo
  git: repo=https://github.com/HackerDom/checksystem.git dest={{cs_dir}}/app
  become: yes
  become_user: "{{cs_user}}"

- name: copy config
  template: src={{cs_conf}} dest={{cs_dir}}/app/c_s.conf owner={{cs_user}} group={{cs_user}}

- name: ensure permissions
  file: path={{cs_dir}}/app owner={{cs_user}} group={{cs_user}} recurse=yes

- name: perl modules
  command: cpanm -n --installdeps {{cs_dir}}/app
  register: r
  changed_when: "r.stdout.find('Found dependencies') != -1"

- name: download telegraf
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.1.0_amd64.deb
    dest: /tmp/telegraf_1.1.0_amd64.deb
    validate_certs: no

- name: install telegraf
  apt:
    deb: /tmp/telegraf_1.1.0_amd64.deb

- name: telegraf config
  template: src=telegraf.conf.j2 dest=/etc/telegraf/telegraf.conf

- name: start telegraf
  command: systemctl restart telegraf
