- name: systemd configs
  template: src=manager.service.j2 dest=/etc/systemd/system/manager.service

- name: systemd configs
  template: src=web.service.j2 dest=/etc/systemd/system/web.service

- name: systemd configs
  template: src=worker.service.j2 dest=/etc/systemd/system/worker.service

- name: systemd configs
  template: src=watcher.service.j2 dest=/etc/systemd/system/watcher.service

- name: systemd reload
  command: systemctl daemon-reload
