- name: systemd configs
  template: src=manager.service.j2 dest=/etc/systemd/system/manager.service

- name: systemd configs
  template: src=web.service.j2 dest=/etc/systemd/system/web.service

- name: systemd configs
  template: src=worker.service.j2 dest=/etc/systemd/system/worker.service

- name: systemd configs
  template: src=watcher.service.j2 dest=/etc/systemd/system/watcher.service

- name: systemd reload
  command: systemctl daemon-reload

- name: nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/cs.conf

- name: sync vis
  synchronize: src=../viz dest=/home/cs

- name: permissions
  file: path=/home/cs/viz owner={{cs_user}} group=www-data recurse=yes
