---
- hosts: image
  gather_facts: True
  vars:
     SSH_PUBLIC_KEY: "{{ lookup('file', '{{ playbook_dir }}/ructfe2016_rsa.pub') }}"
  roles:
    - image
    - lxc
    - general_nginx

- hosts: services
  tasks:
    - name: Install ansible requirements
      apt: name={{ item }} update_cache=yes
      with_items:
        - python
        - sudo
        - ca-certificates

- hosts: pastebin
  gather_facts: True
  roles:
    - pastebin

- hosts: crash
  gather_facts: True
  roles:
    - crash

- hosts: sapmarine
  gather_facts: True
  roles:
    - sapmarine

- hosts: cross-social-science
  gather_facts: True
  roles:
    - cross-social-science

# - hosts: cartographer-build
#   gather_facts: True
#   roles:
#     - cartographer-build

# - hosts: cartographer
#   gather_facts: True
#   roles:
#     - cartographer

- hosts: services
  gather_facts: True
  tasks:
    - name: Fill zeros
      when: "release is defined"
      command: dd if=/dev/zero of=/zero
      ignore_errors: yes
    - name: Remove zeros
      when: "release is defined"
      file: name=/zero state=absent

- hosts: image
  gather_facts: True
  tasks:
    - name: Restart general_nginx
      service: name=nginx state=restarted
    - name: Remove build lxc containers
      when: "release is defined"
      lxc_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - cartographer-build
    - name: Use first_time.sh
      lineinfile: dest=/root/.bashrc line="ONETIME=yes /root/first_time.sh"
      when: "release is defined"
    - name: Remove network file
      file: dest=/etc/network/interfaces.d/eth0.cfg state=absent
      when: "release is defined"
    - name: Fill zeros
      when: "release is defined"
      ignore_errors: yes
      command: dd if=/dev/zero of=/zero
    - name: Remove zeros
      when: "release is defined"
      file: name=/zero state=absent
