---
- hosts: image
  gather_facts: True
  vars:
     SSH_PUBLIC_KEY: "{{ lookup('file', '{{ playbook_dir }}/ructfe2016_rsa.pub') }}"
  roles:
    - noman
    - image
    - lxc
    - general_nginx

- hosts: containers
  roles:
    - noman

- hosts: build
  gather_facts: True
  roles:
    - thebin-build
    - cartographer-build

- hosts: thebin
  gather_facts: True
  roles:
    - thebin

- hosts: crash
  gather_facts: True
  roles:
    - crash

- hosts: sapmarine
  gather_facts: True
  roles:
    - sapmarine
  tasks:
    - name: Remove swift archive
      when: "release is defined"
      file: name=/opt/swift-3.0-RELEASE-ubuntu14.04.tar.gz state=absent

- hosts: atlablog
  gather_facts: True
  roles:
    - atlablog

- hosts: cartographer
  gather_facts: True
  roles:
    - cartographer

- hosts: weather
  gather_facts: True
  roles:
    - weather

- hosts: image
  gather_facts: True
  tasks:
    - name: Restart general_nginx
      service: name=nginx state=restarted
    - name: Remove build lxc container
      when: "release is defined"
      lxc_container: name=build state=absent
    - name: Remove lxc template
      when: "release is defined"
      file: name=/var/cache/lxc/debian state=absent
    - name: Remove history
      when: "release is defined"
      file: name=/root/.bash_history state=absent
    - name: Use first_time.sh
      lineinfile: dest=/root/.bashrc line="ONETIME=yes /root/first_time.sh"
      when: "release is defined"

