---
- hosts: image
  gather_facts: True
  vars:
     SSH_PUBLIC_KEY: "{{ lookup('file', '{{ playbook_dir }}/ructfe2016_rsa.pub') }}"
  roles:
    - image
    - lxc
    - general_nginx

- hosts: services
  tasks:
    - name: Install python-minimal
      raw: "test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)"
      changed_when: False
    - name: Install ansible requirements
      apt: name={{ item }}
      with_items:
        - sudo
        - ca-certificates

- hosts: build
  gather_facts: True
  roles:
    - pastebin-build
    - cartographer-build

- hosts: pastebin
  gather_facts: True
  roles:
    - pastebin

- hosts: crash
  gather_facts: True
  roles:
    - crash

- hosts: sapmarine
  gather_facts: True
  roles:
    - sapmarine

- hosts: cross-social-science
  gather_facts: True
  roles:
    - cross-social-science

- hosts: cartographer
  gather_facts: True
  roles:
    - cartographer

- hosts: image
  gather_facts: True
  tasks:
    - name: Restart general_nginx
      service: name=nginx state=restarted
    - name: Remove build lxc container
      when: "release is defined"
      lxc_container: name=build state=absent
    - name: Use first_time.sh
      lineinfile: dest=/root/.bashrc line="ONETIME=yes /root/first_time.sh"
      when: "release is defined"
    - name: Fill zeros
      when: "release is defined"
      ignore_errors: yes
      command: dd if=/dev/zero of=/zero
    - name: Remove zeros
      when: "release is defined"
      file: name=/zero state=absent
    - name: Poweroff
      shell: rm -f /etc/network/interfaces.d/eth0.cfg && poweroff
      when: "release is defined"
      ignore_errors: yes
      tags:
        - skip_ansible_lint
