---
- name: Stretch | Packages | Add testing repo
  apt_repository: repo='deb http://mirror.yandex.ru/debian stretch main' update_cache=yes

- name: Stretch | Packages | Fix testing priority
  become: yes
  template: src=apt_preferences.j2 dest=/etc/apt/preferences
