---
- name: Set nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf validate="nginx -t -c %s"
  notify: restart nginx

- name: Copy default site
  when: "path_to_site is defined"
  synchronize:
    src: "{{ path_to_site }}"
    dest: "/var/www/"
    recursive: yes
    delete: yes
    use_ssh_args: yes

- name: Create directories for nginx conf
  file: name=/etc/nginx/{{ item }} state=directory
  with_items:
    - web
    - stream

- name: Install nginx configuration file.
  template: src=vhost.conf.j2 dest=/etc/nginx/web/default.conf
  notify: reload nginx

- name: Install service web conf
  template: src=web.service.conf.j2 dest=/etc/nginx/web/{{ item }}.conf
  notify: reload nginx
  with_items:
    - pastebin
    - crash

- name: Install service conf
  template: src=service.conf.j2 dest=/etc/nginx/stream/{{ item.name }}.conf
  notify: reload nginx
  with_items:
    - { name: pastebin, port: 8080, remote_port: 80 }
    - { name: crash, port: 1080 }
